apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    {{- include "fastapi-postgres-ai.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image | quote }}
          imagePullPolicy: {{ .Values.api.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SECRET_KEY
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: OPENROUTER_API_KEY
            - name: OPENROUTER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: OPENROUTER_URL
            - name: OPENROUTER_MODEL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: OPENROUTER_MODEL
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: TAVILY_API_KEY
          readinessProbe:
            httpGet:
              path: /docs
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: {{ .Values.api.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
