apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    {{- include "fastapi-postgres-ai.labels" . | nindent 4 }}
spec:
  selector:
    app: api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      {{- with .Values.api.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  type: {{ .Values.api.service.type }}
