apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: fastapi-postgres
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: fastapi-postgres-ai:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENROUTER_API_KEY
            - name: OPENROUTER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENROUTER_URL
            - name: OPENROUTER_MODEL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENROUTER_MODEL
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TAVILY_API_KEY
          readinessProbe:
            httpGet:
              path: /docs
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
