apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fastapi-postgres
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: dzservice
  OPENROUTER_URL: https://openrouter.ai/api/v1
