apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fastapi-postgres
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "123456"
  SECRET_KEY: "REPLACE_WITH_YOUR_JWT_SECRET_KEY"
  OPENROUTER_API_KEY: "REPLACE_WITH_YOUR_OPENROUTER_API_KEY"
  OPENROUTER_URL: "https://openrouter.ai/api/v1"
  OPENROUTER_MODEL: "openrouter/free"
  TAVILY_API_KEY: "REPLACE_WITH_YOUR_TAVILY_API_KEY"
